
title: Wayne's Corner
description: >- # this means to ignore newlines until "baseurl:"
  Be humble, be curious — the path to discovering the world and oneself.

url: "https://wayne82.github.io" # the base hostname & protocol for your site
github_username: wayne82
author:
  name: Wayne Wang
  email: wynw82@gmail.com

# User remote theme minima on Github
remote_theme: jekyll/minima@ded17a1
plugins:
  - jekyll-feed
  - jekyll-remote-theme

show_excerpts: true
google_analytics: G-7QQBEZL21K

minima:
  social_links:
    - title: Wayne's Github
      icon: github
      url: https://github.com/Wayne82
    - title: Wayne's LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/wayne82